name: autofix.ci

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  apply:
    name: Apply automated fixes
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor != 'renovate[bot]' && ! contains(github.event.head_commit.author.name , 'renovate[bot]') && ! contains(github.event.head_commit.message , 'chore(release)') }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup toolchains
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
      - name: Install Dependencies
        run: bun ci
      - name: Format code
        run: bun biome check --write
      - name: Fix package.json
        run: bun syncpack fix
      - name: Format package.json
        run: bun syncpack format
      - name: Update package lock file
        run: bun install --lockfile-only
      - name: Submit autofix
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
        with:
          fail-fast: false
