name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: Install dependencies
        run: bun ci
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: bun bench
          token: ${{ secrets.CODSPEED_TOKEN }}
